# Generated by Django 2.0.4 on 2018-05-15 15:40

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flexion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singulier', models.CharField(max_length=100)),
                ('pluriel', models.CharField(max_length=100)),
                ('fréquence', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('dictionnaires', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), null=True, size=None)),
                ('liens', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('libelles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=None)),
                ('notes_internes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('note_externe', models.TextField(blank=True)),
                ('validation', models.CharField(choices=[('générer', 'Générer'), ('à-valider', 'À valider'), ('erreur', 'Erreur signalé'), ('non-valide', 'Non-valide'), ('valide', 'Valide')], default='à-valider', max_length=30)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masculin_singulier', models.CharField(max_length=100)),
                ('masculin_pluriel', models.CharField(max_length=100)),
                ('fréquence', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('terminaison', models.CharField(blank=True, choices=[('e', 'e'), ('eur', 'eur')], help_text='Catégorie de la terminaison du mot', max_length=25)),
                ('notes_internes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('note_externe', models.TextField(blank=True, help_text='Texte a montrer au utilisateur')),
                ('validation', models.CharField(choices=[('générer', 'Générer'), ('à-valider', 'À valider'), ('erreur', 'Erreur signalé'), ('non-valide', 'Non-valide'), ('valide', 'Valide')], default='à-valider', max_length=25)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlexionFéminine',
            fields=[
                ('flexion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mots.Flexion')),
            ],
            bases=('mots.flexion',),
        ),
        migrations.CreateModel(
            name='FlexionMasculine',
            fields=[
                ('flexion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mots.Flexion')),
            ],
            bases=('mots.flexion',),
        ),
        migrations.AddField(
            model_name='flexion',
            name='mot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mots.Mot'),
        ),
    ]
