# Generated by Django 2.0.4 on 2018-05-15 16:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mot',
            name='masculin_pluriel_autres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
        migrations.AddField(
            model_name='mot',
            name='masculin_sinuglier_autres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
    ]
